project:
  type: website

website:
  title: "Sharon Jepkosgei"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Courses
        href: research.qmd
      - text: "Database project"
        menu:
          - href: "Final Presentation.pdf"
            text: "Final presentation"
          - href: "Sharon_Jepkosgei_Project_epps6354.pdf"
            text: "Final Paper"
          - href: "Database Proposal Presentation.pdf"
            text: "Proposal Presentation"
      - href: "https://sharonjepkosgei.shinyapps.io/ExploreApp/"
        text: "Explore Care App"
      - href: "Sharon CV.pdf"
        text: "CV"
      
      
            
format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    fontsize: 1.2em
    mainfont: Open Sans
    monofont: playfair

editor: visual
