---
title: "Courses"
---

## Semester
- [Fall 2023](#fall-2023)

- [Spring 2023](#spring-2023)
  

### Fall 2023

- [EPPS 6302: Data Collection & Production](#EPPS: Data Methods-fall-2023)
  - [Assignment 1](Assignment.pdf)
- [EPPS 6356: Data Visualization](#EPPS: Data Visualization-fall-2023)

### Spring 2023

#### [EPPS 6354: Information Management](#epps-6354-spring-2023)

<details>
<summary>Course Description</summary>

This course introduces students to the use of economic methods of the analysis of public policy.A variety of public policy topics are covered including education, employment and the labor market, taxes and redistribution, access to health care, poverty and inequality, and public assistance programs.


</details>

  - [Assignment 1](EPPS 6354 Assignment 1.pdf)
  - [Assignment 2](EPPS 6354 Assignment 2.pdf)
  - [Assignment 3](EPPS 6354 Assignment 3.pdf)
  - [Assignment 4](EPPS 6354 Assignment 4.pdf)
  - [Assignment 5](EPPS 6354 Assignment 5.pdf)
  - [Assignment 6](EPPS 6354 Assignment 6.pdf)
  
  
#### [PPPE 6321: Economics of Public Policy](#epps-6330-spring-2023)

 <details>
 <summary>Course Description</summary>

This course introduces students to the use of economic methods of the analysis of public policy.A variety of public policy topics are covered including education, employment and the labor market, taxes and redistribution, access to health care, poverty and inequality, and public assistance programs.


 </details>

  - [Research Paper](Final_Paper_PPPE6321_SP23_GroupB)




